force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Average_Rating__c.field-meta.xml
<CustomField>
    <fullName>Average_Rating__c</fullName>
    <label>Average_Rating</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>45</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book_Rating__c/Book_Rating__c.object-meta.xml
<CustomObject>
    <label>Book Rating</label>
    <nameField>
        <label>Book Rating Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Book Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Rating__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Book Ratings</relationshipLabel>
    <relationshipName>Book_Ratings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Book_Rating__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Book_Rating__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>User</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Book Ratings</relationshipLabel>
    <relationshipName>Book_Ratings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <label>Nickname</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BookRatingTriggerTest.cls
@isTest
private class BookRatingTriggerTest {
    @TestSetup
    static void makeData() {
        User__c user = TestDataFactory.createReaderUsers(true, 1, 'Test', 'reader@test.com').get(0);
        Author__c author = TestDataFactory.createAuthors(true, 1, 'Autor', 'Autorski').get(0);
        Book__c book = TestDataFactory.createBooks(true, 1, 'Wiedźmin', author.Id).get(0);
    }

    @isTest
    static void bookRatingInsertTest() {
        Book__c book = [SELECT Id, Average_Rating__c FROM Book__c WHERE Title__c = 'Wiedźmin'].get(0);
        User__c user = [SELECT Id FROM User__c WHERE Nickname__c = 'Test'].get(0);

        Book_Rating__c bookRating = TestDataFactory.createBookRating(false, book.Id, user.Id, 3);
        Test.startTest();
        Database.SaveResult result = Database.insert(bookRating);
        Test.stopTest();

        System.assert(result.isSuccess());
        System.assertEquals(3, [SELECT Id, Average_Rating__c FROM Book__c WHERE Title__c = 'Wiedźmin'].get(0).Average_Rating__c);
    }

    @isTest
    static void bookRatingUpdateTest() {
        Book__c book = [SELECT Id, Average_Rating__c FROM Book__c WHERE Title__c = 'Wiedźmin'].get(0);
        User__c user = [SELECT Id FROM User__c WHERE Nickname__c = 'Test'].get(0);

        Book_Rating__c bookRating = TestDataFactory.createBookRating(true, book.Id, user.Id, 3);
        Test.startTest();
        bookRating.Rating__c = 10;
        Database.SaveResult result = Database.update(bookRating);
        Test.stopTest();

        System.assert(result.isSuccess());
        System.assertEquals(10, [SELECT Id, Average_Rating__c FROM Book__c WHERE Title__c = 'Wiedźmin'].get(0).Average_Rating__c);
    }

    @isTest
    static void bookRatingDeleteTest() {
        Book__c book = [SELECT Id, Average_Rating__c FROM Book__c WHERE Title__c = 'Wiedźmin'].get(0);
        User__c user = [SELECT Id FROM User__c WHERE Nickname__c = 'Test'].get(0);

        Book_Rating__c bookRating = TestDataFactory.createBookRating(true, book.Id, user.Id, 3);
        Test.startTest();
        Database.DeleteResult result = Database.delete(bookRating);
        Test.stopTest();

        System.assert(result.isSuccess());
        System.assertEquals(0, [SELECT Id, Average_Rating__c FROM Book__c WHERE Title__c = 'Wiedźmin'].get(0).Average_Rating__c);
    }
}