force-app/main/default/objects/Book__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>45</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discussion__c/Discussion__c.object-meta.xml
<CustomObject>
    <label>Discussion</label>
    <nameField>
        <label>Discussion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discussion__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Discussions</relationshipLabel>
    <relationshipName>Discussions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discussion__c/fields/First_Post__c.field-meta.xml
<CustomField>
    <fullName>First_Post__c</fullName>
    <label>First Post</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Discussion__c/fields/Post_Number__c.field-meta.xml
<CustomField>
    <fullName>Post_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Post Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discussion__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>User</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Discussions</relationshipLabel>
    <relationshipName>Discussions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <label>Nickname</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DiscussionController.cls
public with sharing class DiscussionController {

    @AuraEnabled(cacheable=true)
    public static List<Discussion__c> getDiscussion(id discussionId){
        try {
            List<Discussion__c> discussion = [SELECT Book__r.Title__c, User__r.Photo__c,Post_Number__c, Title__c,CreatedDate, User__r.Nickname__c,  First_Post__c FROM Discussion__c WHERE Id =:discussionId ];
            return discussion;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Discussion__c> getAllDiscussions(id bookId){
        try {
            List<Discussion__c> discussions = [SELECT Book__r.Title__c, Post_Number__c, Title__c,CreatedDate, User__r.Nickname__c, User__r.Photo__c FROM Discussion__c WHERE Book__r.Id =: bookId];
            return discussions;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
   
}