force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Only Reviewer or Admin can create Reviews.</errorMessage>
        <filterItems>
            <field>User__c.Role__c</field>
            <operation>equals</operation>
            <value>Reviewer</value>
        </filterItems>
        <filterItems>
            <field>User__c.Role__c</field>
            <operation>equals</operation>
            <value>Admin</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review_Rating__c/Review_Rating__c.object-meta.xml
<CustomObject>
    <label>Review Rating</label>
    <nameField>
        <label>Review Rating Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review_Rating__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <label>Review</label>
    <referenceTo>Review__c</referenceTo>
    <relationshipLabel>Review Ratings</relationshipLabel>
    <relationshipName>Review_Ratings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Review_Rating__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>User</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Review Ratings</relationshipLabel>
    <relationshipName>Review_Ratings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ReviewRatingController.cls
public class ReviewRatingController {
    @AuraEnabled
    public static Review_Rating__c addReviewRating(Id reviewId, Id bookwormUserId, Boolean isLike) {
        Review_Rating__c reviewRating = new Review_Rating__c(Review__c = reviewId, Like__c = isLike, User__c = bookwormUserId);
        try {
            insert reviewRating;
            return reviewRating;
        } catch (DmlException e) {
            System.debug(e.getMessage());
        }
        return null;
    }

    @AuraEnabled(cacheable=true)
    public static Review_Rating__c userHasRatingReview(Review__c review, Id bookwormUserId) {
    List<Review_Rating__c> reviewRating = [SELECT Id, Like__c, User__c, Review__c FROM Review_Rating__c WHERE Review__c = :review.Id AND User__c = :bookwormUserId LIMIT 1];
        if(reviewRating.size() > 0){
            return reviewRating[0];
        }
        else{
            return null;
        }
        

    }

    @AuraEnabled
    public static Review_Rating__c changeReviewRating(Review_Rating__c reviewRating, Boolean isLike) {
        reviewRating.Like__c = isLike;
        try {
            update reviewRating;
            return reviewRating;
        } catch (DmlException e) {
            System.debug(e.getMessage());
        }
        return null;
    }

    @AuraEnabled
    public static Review_Rating__c deleteReviewRating(Review_Rating__c reviewRating) {
        try {
            delete reviewRating;
            return reviewRating;
        } catch (DmlException e) {
            System.debug(e.getMessage());
        }
        return null;
    }
}