force-app/main/default/objects/Book_Rating__c/Book_Rating__c.object-meta.xml
<CustomObject>
    <label>Book Rating</label>
    <nameField>
        <label>Book Rating Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Book Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Rating__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Book Ratings</relationshipLabel>
    <relationshipName>Book_Ratings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Book_Rating__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Book_Rating__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>User</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Book Ratings</relationshipLabel>
    <relationshipName>Book_Ratings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/fields/Alt__c.field-meta.xml
<CustomField>
    <fullName>Alt__c</fullName>
    <label>Alt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <label>Nickname</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User__c/fields/SFUser__c.field-meta.xml
<CustomField>
    <fullName>SFUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SFUser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SFUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BookRatingController.cls
public class BookRatingController {
    @AuraEnabled(cacheable=true)
    public static List<Book_Rating__c> getBookRatings(Id bookId) {
        return [
            SELECT Id, Book__c, Comment__c, Rating__c, CreatedDate, User__c, User__r.SFUser__c, User__r.Photo__c, User__r.Alt__c, User__r.Nickname__c
            FROM Book_Rating__c
            WHERE Book__c = :bookId
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Book_Rating__c userHasBookRating(List<Book_Rating__c> bookRatings, Id SFuserId) {
        for (Book_Rating__c bookRating : bookRatings) {
            if (bookRating.User__r.SFUser__c == SFuserId) {
                return bookRating;
            }
        }
        return null;
    }

    @AuraEnabled(cacheable=true)
    public static Book_Rating__c addBookRating(Id bookId, Id bookwormUserId, String comment, Decimal rating) {
        Book_Rating__c bookRating = new Book_Rating__c(Book__c = bookId, Rating__c = rating, Comment__c = comment, User__c = bookwormUserId);

        try {
            insert bookRating;
            return bookRating;
        } catch (DmlException e) {
            System.debug(e.getMessage());
        }
        return null;
    }

    @AuraEnabled(cacheable=true)
    public static Book_Rating__c editBookRating(Book_Rating__c oldRating, String comment, Decimal rating) {
        oldRating.Comment__c = comment;
        oldRating.Rating__c = rating;

        try {
            update oldRating;
            return oldRating;
        } catch (DmlException e) {
            System.debug(e.getMessage());
        }
        return null;
    }

    @AuraEnabled(cacheable=true)
    public static Book_Rating__c deleteBookRating(Id SFuserId) {
        Book_Rating__c deletedBookRating = [
            SELECT Id, Book__c, Comment__c, Rating__c, CreatedDate, User__c, User__r.SFUser__c, User__r.Photo__c, User__r.Alt__c, User__r.Nickname__c
            FROM Book_Rating__c
            WHERE User__r.SFUser__c = :SFuserId
        ];
        try {
            delete deletedBookRating;
            return deletedBookRating;
        } catch (DmlException e) {
            System.debug(e.getMessage());
        }
        return null;
    }
}