force-app/main/default/objects/Discussion__c/Discussion__c.object-meta.xml
<CustomObject>
    <label>Discussion</label>
    <nameField>
        <label>Discussion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discussion__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>User</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Discussions</relationshipLabel>
    <relationshipName>Discussions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Post__c/Post__c.object-meta.xml
<CustomObject>
    <label>Post</label>
    <nameField>
        <label>Post Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Post__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/Discussion__c.field-meta.xml
<CustomField>
    <fullName>Discussion__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Discussion</label>
    <referenceTo>Discussion__c</referenceTo>
    <relationshipLabel>Posts</relationshipLabel>
    <relationshipName>Posts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>User</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Posts</relationshipLabel>
    <relationshipName>Posts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <label>Nickname</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PostController.cls
public with sharing class PostController {
    @AuraEnabled(cacheable=true)
    public static List<Post__c> getAllPosts(id discussionId){
        try {
            List<Post__c> posts = [SELECT Id, User__r.Nickname__c, User__r.Photo__c, CreatedDate, Content__c  FROM Post__c WHERE Discussion__r.Id =: discussionId];
            return posts;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Post__c createPost(String content, id userId, id discussionId){
        Post__c newPost = new Post__c(Content__c = content, User__c = userId, Discussion__c = discussionId);
        try {
           
            insert newPost;
            return newPost;
            
        } catch (DmlException e) {
            System.debug(e.getMessage());
        }
        System.debug('jakas wiadomosc');
        return null;
    }

    @AuraEnabled
    public static Post__c updatePost(Post__c post, String content) {
        post.Content__c = content;
        try {
            update post;
            return post;
        } catch (DmlException e) {
            System.debug(e.getMessage());
        }
        return null;
    }

    @AuraEnabled
    public static Post__c deletePost(Post__c post) {
        try {
            delete post;
            return post;
        } catch (DmlException e) {
            System.debug(e.getMessage());
        }
        return null;
    }
}