force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/fields/Alt__c.field-meta.xml
<CustomField>
    <fullName>Alt__c</fullName>
    <label>Alt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <label>Nickname</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reader</fullName>
                <default>true</default>
                <label>Reader</label>
            </value>
            <value>
                <fullName>Reviewer</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
                <isActive>false</isActive>
                <label>Admin</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User__c/fields/SFUser__c.field-meta.xml
<CustomField>
    <fullName>SFUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SFUser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SFUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserController.cls
public with sharing class UserController {
    @AuraEnabled(cacheable=true)
    public static User__c getBookwormUser(Id SFUserId) {
        return [SELECT Id, Alt__c, Email__c, Nickname__c, SFUser__c, Photo__c, Role__c FROM User__c WHERE SFUser__c = :SFUserId LIMIT 1];
    }

    @AuraEnabled
    public static User__c changeNickname(Id SFUserId, String nickname) {
        User__c bookwormUser = getBookwormUser(SFUserId);
        bookwormUser.Nickname__c = nickname;
        try {
            update bookwormUser;
            return bookwormUser;
        } catch (DmlException e) {
            System.debug(e.getMessage());
        }
        return null;
    }
}