force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <label>Nickname</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reader</fullName>
                <default>true</default>
                <label>Reader</label>
            </value>
            <value>
                <fullName>Reviewer</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
                <isActive>false</isActive>
                <label>Admin</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User__c/fields/SFUser__c.field-meta.xml
<CustomField>
    <fullName>SFUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SFUser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SFUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserTriggerHelper.cls
public class UserTriggerHelper {
    public static void createBookwormUser(Map<Id, sObject> oldUsers, List<User> newUsers) {
        List<User__c> bookwormUsers = new List<User__c>();
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Bookworm Customers' LIMIT 1];
        for (User user : newUsers) {
            if (user.ProfileId == profile.Id) {
                bookwormUsers.add(new User__c(Nickname__c = user.Username, Email__c = user.Email, Role__c = 'Reader', SFUser__c = user.Id));
            }
        }

        try {
            insert bookwormUsers;
        } catch (DmlException e) {
            System.debug(e.getMessage());
        }
    }
}