force-app/main/default/objects/Author__c/fields/Date_Of_Death__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Death__c</fullName>
    <label>Date Of Death</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Author__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Author__c/fields/Photo__c.field-meta.xml
<CustomField>
    <fullName>Photo__c</fullName>
    <label>Photo</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Author__c/fields/Surname__c.field-meta.xml
<CustomField>
    <fullName>Surname__c</fullName>
    <label>Surname</label>
    <length>90</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>45</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AuthorController.cls
public class AuthorController {
    @AuraEnabled(cacheable=true)
    public static Author__c getAuthor(Id authorId) {
        return [SELECT Id, Name__c, Surname__c, Photo__c, Alt__c, Date_Of_Birth__c, Date_Of_Death__c, Description__c FROM Author__c WHERE Id = :authorId LIMIT 1];
    }

    @AuraEnabled(cacheable=true)
    public static List<Book__c> getBooksByAuthor(Id authorId) {
        return [SELECT Id, Title__c, Author__c, Author__r.Name__c, Author__r.Surname__c, Photo__c, Alt__c FROM Book__c WHERE Author__c = :authorId];
    }
}