force-app/main/default/objects/Author__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Author__c/fields/Photo__c.field-meta.xml
<CustomField>
    <fullName>Photo__c</fullName>
    <label>Photo</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Author__c/fields/Surname__c.field-meta.xml
<CustomField>
    <fullName>Surname__c</fullName>
    <label>Surname</label>
    <length>90</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Book_Series__c.field-meta.xml
<CustomField>
    <fullName>Book_Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book Series</label>
    <referenceTo>Book_Series__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>45</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book_Series__c/Book_Series__c.object-meta.xml
<CustomObject>
    <label>Book Series</label>
    <nameField>
        <label>Book Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Book Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BookSeriesController.cls
public class BookSeriesController {
    @AuraEnabled(cacheable=true)
    public static List<Book__c> getBooksFromSeries(Id bookSeriesId) {
        try {
            List<Book__c> books = [
                SELECT Id, Title__c, Photo__c, Alt__c, Book_Series__c, Book_Series__r.Name, Author__c, Author__r.Name__c, Author__r.Surname__c
                FROM Book__c
                WHERE Book_Series__c = :bookSeriesId
                ORDER BY CreatedDate
            ];
            return books;
        } catch (DmlException e) {
            System.debug(e.getMessage());
        }
        return null;
    }
}