force-app/main/default/objects/Author__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Author__c/fields/Surname__c.field-meta.xml
<CustomField>
    <fullName>Surname__c</fullName>
    <label>Surname</label>
    <length>90</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>45</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book_List_Item__c/Book_List_Item__c.object-meta.xml
<CustomObject>
    <label>Book List Item</label>
    <nameField>
        <label>Book List Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Book List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_List_Item__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Book List Items</relationshipLabel>
    <relationshipName>Book_List_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Book_List_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chcę przeczytać</fullName>
                <default>true</default>
                <label>Chcę przeczytać</label>
            </value>
            <value>
                <fullName>W trakcie czytania</fullName>
            </value>
            <value>
                <fullName>Przeczytane</fullName>
            </value>
            <value>
                <fullName>Porzucone</fullName>
            </value>
            <value>
                <fullName>Na półce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Book_List_Item__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>User</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Book List Items</relationshipLabel>
    <relationshipName>Book_List_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BookListController.cls
public with sharing class BookListController {
    @AuraEnabled(cacheable=true)
    public static List<Book_List_Item__c> getUserBooks(Id bookwormUserId) {
        try {
            List<Book_List_Item__c> bookList = [
                SELECT Id, Book__c, Book__r.Title__c, Book__r.Author__c, Book__r.Author__r.Name__c, Book__r.Author__r.Surname__c, Status__c
                FROM Book_List_Item__c
                WHERE User__r.Id = :bookwormUserId
            ];
            return bookList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static Book_List_Item__c addBookListItem(Id bookId, Id bookwormUserId, String status) {
        Book_List_Item__c bookListItem;
        if (status == null || status == '') {
            bookListItem = new Book_List_Item__c(Book__c = bookId, User__c = bookwormUserId);
        } else {
            bookListItem = new Book_List_Item__c(Book__c = bookId, User__c = bookwormUserId, Status__c = status);
        }

        try {
            insert bookListItem;
            return bookListItem;
        } catch (DmlException e) {
            System.debug(e.getMessage());
        }
        return null;
    }

    @AuraEnabled(cacheable=true)
    public static Book_List_Item__c changeBookListItemStatus(Book_List_Item__c bookListItem, String newStatus) {
        bookListItem.Status__c = newStatus;

        try {
            update bookListItem;
            return bookListItem;
        } catch (DmlException e) {
            System.debug(e.getMessage());
        }
        return null;
    }

    @AuraEnabled(cacheable=true)
    public static Book_List_Item__c deleteBookListItem(Book_List_Item__c bookListItem) {
        try {
            delete bookListItem;
            return bookListItem;
        } catch (DmlException e) {
            System.debug(e.getMessage());
        }
        return null;
    }
}