force-app/main/default/objects/Author__c/fields/Photo__c.field-meta.xml
<CustomField>
    <fullName>Photo__c</fullName>
    <label>Photo</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Average_Rating__c.field-meta.xml
<CustomField>
    <fullName>Average_Rating__c</fullName>
    <label>Average_Rating</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Book_Series__c.field-meta.xml
<CustomField>
    <fullName>Book_Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book Series</label>
    <referenceTo>Book_Series__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adventure</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Dystopian</fullName>
            </value>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>Historical fiction</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Mystery</fullName>
            </value>
            <value>
                <fullName>Romance</fullName>
            </value>
            <value>
                <fullName>Science Fiction</fullName>
            </value>
            <value>
                <fullName>Thriller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Book__c/fields/Pages__c.field-meta.xml
<CustomField>
    <fullName>Pages__c</fullName>
    <label>Pages</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>45</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book_Series__c/Book_Series__c.object-meta.xml
<CustomObject>
    <label>Book Series</label>
    <nameField>
        <label>Book Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Book Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BookController.cls
public with sharing class BookController {
    @AuraEnabled
    public static Book__c getBook(id bookId){
        try {
            Book__c book = [SELECT Genre__c, Title__c, Pages__c, Release_Date__c, 
            Book_Series__r.Id, Book_Series__r.Name, Author__r.Id, Author__r.Name, Photo__c, Average_Rating__c FROM Book__c WHERE Id =: bookId];
            System.debug(book);
            return book;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static List<Book__c> getAllBooks(){
        try {
            List<Book__c> books = [SELECT Genre__c, Title__c, Pages__c, Release_Date__c, 
            Book_Series__r.Id, Book_Series__r.Name, Author__r.Id, Author__r.Name, Photo__c, Average_Rating__c FROM Book__c];
            System.debug(books);
            return books;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Book__c> getAllBooksByGenre(String genre){
        try {
            List<Book__c> books = [SELECT Genre__c, Title__c, Pages__c, Release_Date__c, 
            Book_Series__r.Id, Book_Series__r.Name, Author__r.Id, Author__r.Name, Photo__c, Average_Rating__c FROM Book__c 
            WHERE Genre__c INCLUDES(:genre)];
            System.debug(books.size());
            return books;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static List<Book__c> getAllBooksToRanking(){
        try {
            List<Book__c> books = [SELECT Genre__c, Title__c, Pages__c, Release_Date__c, 
            Book_Series__r.Id, Book_Series__r.Name, Author__r.Id, Author__r.Name, Photo__c, Average_Rating__c FROM Book__c ORDER BY Average_Rating__c  DESC NULLS LAST LIMIT 20];
    
            for (Book__c el : books) {
                System.debug(el.Average_Rating__c);
            }
            return books;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}


        // List<Book__c>  newBooks = new List<Book__c>();

            // Map<Double, Book__c> ratingWithBookMap = new Map<Double, Book__c>();
            // for (Book__c el : books) {
            //     ratingWithBookMap.put(el.Average_Rating__c, el);
            // }


            // for (Book__c el : books) {
                
            // }

            // System.debug('-----------------');
            // books.sort();